baseURL = "https://inspiring-kilby-bb1bde.netlify.app/"
languageCode = "en-us"
title = "ICT 302 Hugo"
theme = "soho-master"

[params]
  author = "Zahra Khan"
  description = "This a student blog for content management class."
  profilePicture = "https://inspiring-kilby-bb1bde.netlify.app/elephant.png"
  themeColor = "#bd1167"

[[menu.main]]
name = "About"
weight = 1
url = "https://inspiring-kilby-bb1bde.netlify.app/introduction/"

[[menu.main]]
name = "Annotated Definitions"
weight = 2
url = "https://inspiring-kilby-bb1bde.netlify.app/annotateddefinitions/"

[[menu.main]]
name = "Resource Guide"
weight = 3
url = "https://inspiring-kilby-bb1bde.netlify.app/resourceguide/"

[[menu.main]]
name = "Walkthrough"
weight = 4
url = "https://inspiring-kilby-bb1bde.netlify.app/walkthrough/"

[[menu.main]]
name = "Testing"
weight = 5
url = "https://inspiring-kilby-bb1bde.netlify.app/testing/"

[params.style]
  darkestColor = "#C2027B"
  darkColor = "#060732"
  primaryColor ="#82f69b"
  lightColor = "#F8F8F8"
  lightestColor ="#fff8ad"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


